const jsondata = [
    {
        "id": "1",
        "icon": "http://icons.wxug.com/i/c/k/clear.gif",
        "name": "Jon",
        "locked": true,
        "color template": "Airi ",
        "coins balance": "No",
        "time limit": "5",
        "performance": "Time",
        "number of skins": "Female",
        "live": true,
        "last update": 22
    },
    {
        "id": "2",
        "icon": "http://icons.wxug.com/i/c/k/clear.gif",
        "name": "sadf",
        "locked": true,
        "color template": "adsf",
        "coins balance": "Yes",
        "time limit": "7",
        "performance": "Time",
        "number of skins": "Female",
        "live": false,
        "last update": 23
    },
    {
        "id": "3",
        "icon": "http://icons.wxug.com/i/c/k/clear.gif",
        "name": "Qxczv",
        "locked": true,
        "color template": "cvb",
        "coins balance": "No",
        "time limit": "8",
        "performance": "Time",
        "number of skins": "Female",
        "live": true,
        "last update": 24
    },
    {
        "id": "4",
        "icon": "http://icons.wxug.com/i/c/k/clear.gif",
        "name": "adfb",
        "locked": true,
        "color template": "trru",
        "coins balance": "Yes",
        "time limit": "10",
        "performance": "Time",
        "number of skins": "Female",
        "live": true,
        "last update": 25
    },
    {
        "id": "5",
        "icon": "http://icons.wxug.com/i/c/k/clear.gif",
        "name": "Services",
        "locked": true,
        "color template": "okj",
        "coins balance": "No",
        "time limit": "21",
        "performance": "Time",
        "number of skins": "Female",
        "live": false,
        "last update": 26
    },
    {
        "id": "6",
        "icon": "http://icons.wxug.com/i/c/k/clear.gif",
        "name": "Computer Services",
        "locked": true,
        "color template": "cxv",
        "coins balance": "No",
        "time limit": "14",
        "performance": "Time",
        "number of skins": "Female",
        "live": false,
        "last update": 27
    },
    {
        "id": "7",
        "icon": "http://icons.wxug.com/i/c/k/clear.gif",
        "name": "aum sdaf Services",
        "locked": true,
        "color template": "dfgh",
        "coins balance": "Yes",
        "time limit": "11",
        "performance": "Time",
        "number of skins": "Female",
        "live": false,
        "last update": 28
    },
    {
        "id": "8",
        "icon": "http://icons.wxug.com/i/c/k/clear.gif",
        "name": "asdxcces",
        "locked": true,
        "color template": "asdkl",
        "coins balance": "No",
        "time limit": "18",
        "performance": "Time",
        "number of skins": "Female",
        "live": true,
        "last update": 29
    },
    {
        "id": "9",
        "icon": "http://icons.wxug.com/i/c/k/clear.gif",
        "name": "asdxcces",
        "locked": true,
        "color template": "kl",
        "coins balance": "No",
        "time limit": "18",
        "performance": "Time",
        "number of skins": "Female",
        "live": false,
        "last update": 29
    }
]

export { jsondata };
